### ISSUE TITLE
More compact way to add traits in JobDSL Configuration Blocks

### ISSUE THREAD

**Issue by superbob** [ftclausen/ftclausen.github.io#4]
## Summary

Hello,

Having read `_posts/2020-04-30-jenkins-jobdsl-git-traits.markdown`, I've found a more compact solution:

```
branchSources {
	branchSource {
		source {
			git {
				id(...)
				remote(...)
				traits {
					gitBranchDiscovery()
					localBranchTrait()
				}
			}
		}
	}
}
```

This seems more idiomatic to Jenkins jobdsl.

Regards.

**Comment by ftclausen** [comment]
Thanks for taking the time to mention that. I'll update the post soon

**Comment by ftclausen** [comment]
Are you able to get this working specifically with the GitLFSPullTrait and CheckoutOptionTrait? It seems like some traits are not accessible other than through configure blocks. If you have a working example that'd be appreciated. 

I think my use of cloneOptionTrait is also not current

**Comment by ftclausen** [comment]
Thanks again for the suggestion (ignore my previous accidental comment) - I have [updated the post](https://ftclausen.github.io/infra/jenkins/jenkins-jobdsl-git-traits/) and it works in my testing.
